# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _DNSProviders

class _Namecheap(_DNSProviders):
    _type = "namecheap"
    _icon_dir = "resources/dnsproviders/namecheap"


class Namecheap(_Namecheap):
    _icon = "namecheap.png"
class Namecheap_Api(_Namecheap):
    _icon = "namecheap_api.png"
class Namecheap_Domain(_Namecheap):
    _icon = "namecheap_domain.png"

# Aliases
